### ISSUE TITLE
Arduino.h:43:26: fatal error: pins_arduino.h: No such file

### ISSUE THREAD

**Issue by gyzhang123** [RTduino/RTduino#33]
大佬，
      这个问题怎么解决

**Comment by mysterywolf** [comment]
请仔细阅读readme文档，这个软件包需要适配具体的BSP，不可以上来就用，arduino_pinout就是BSP一侧需要提供的引脚映射表

**Comment by mysterywolf** [comment]
https://github.com/RTduino/RTduino#5-rtduino%E7%B2%BE%E7%AE%80%E6%A8%A1%E5%BC%8F%E5%BF%AB%E9%80%9F%E4%BD%BF%E7%94%A8%E6%97%A0%E9%9C%80%E9%80%82%E9%85%8D%E7%89%B9%E5%AE%9Absp

你好 我增加了不用适配特定BSP的精简模式，可以尝试一下

**Comment by liangz678** [comment]
#ifndef RTDUINO_TINY_MODE
#include <pins_arduino.h>
#endif
我在menuconfig里面关掉了RTDUINO_TINY_MODE这个宏定义，并且整个工程检索了一遍也没看到哪里有RTDUINO_TINY_MODE的宏定义，为什么#include <pins_arduino.h>会被编译，并且报错呢？

**Comment by mysterywolf** [comment]
https://github.com/RTduino/RTduino/blob/master/core/Arduino.h#L51 在这里定义的
