### ISSUE TITLE
After enabling the RTduino: Arduino Ecological Compatibility Layer, it cannot be built.

### ISSUE THREAD

**Issue by paulcastor30** [RTduino/RTduino#99]
I am using the Renesas RA6M3 HMI Board, which is currently supported by RTduino. However, after I enable the RTduino on the RT-Thread settings, I cannot build it due to linker script problem. 

I am using GNU Tools for ARM Embedded Version 10.2.1 (2021-03-02).

The specific error was inputted below:

14:19:19 **** Incremental Build of configuration Debug for project templatetrial2 ****
make -j8 all 
linking...
c:/rt-threadstudio/repo/extract/toolchain_support_packages/arm/gnu_tools_for_arm_embedded_processors/10.2.1/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld.exe: cannot open linker script file memory_regions.ld: No such file or directory
collect2.exe: error: ld returned 1 exit status
make: *** [makefile:95: rtthread.elf] Error 1
"make -j8 all" terminated with exit code 2. Build might be incomplete.

14:19:20 Build Failed. 2 errors, 0 warnings. (took 550ms)

**Comment by kurisaW** [comment]
@paulcastor30 hello, as for the issue you raised, we have fixed it in the latest commit, you just need to update your rt-thread source code and import it into studio to solve the issue.

* https://github.com/RT-Thread/rt-thread/pull/8684

**Comment by paulcastor30** [comment]
Thank you very much @kurisaW. Let me try it again.
